# https://www.youtube.com/watch?v=YGrfexNwsFU
  # minute 9.30

services:
  app:
    build: .
    container_name: fastapi-channel-api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - .:/app